inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

RSpec/ExampleLength:
  Max: 21

RSpec/VerifiedDoubleReference:
  EnforcedStyle: string

Style/Documentation:
  Enabled: false

require:
  - rubocop-rails
  - rubocop-rspec
